### ISSUE TITLE
Would a version of a lock files make sense for external dependencies?

### ISSUE THREAD

**Issue by miguelsolano** [ry/deno#217] opened 2018-06-08 23:49 UTC
I am aware of the --reload flag, but would it make sense to include a version of a lockfile that is only updated with the --reload? I am hesitant to create this issue because if the dependencies are pulled in with URLs then it's irrelevant due to the fact that the cache becomes the source of truth, but would it make sense?

**Comment by kitsonk** [comment] 2018-06-09 00:47
Essentially a duplicate of discussion on #213

**Comment by ry** [comment] 2018-06-09 09:43
Yes, a lock file is probably the way to go for security. However in the near future, I won't invest engineering effort into that since there are more fundamental issues to be dealt with. (Also I'd rather not take PRs for lock files yet either.)

**Closed by ry** 2018-06-09 09:43 UTC
