### ISSUE TITLE
when i run ./build.py --use_ccache ,there was a mistake

### ISSUE THREAD

**Issue by lvgithub** [ry/deno#60] opened 2018-06-01 01:38 UTC
![image](https://user-images.githubusercontent.com/16065346/40816486-da7a3bf0-657f-11e8-9f63-2c6b9e2c6347.png)

go get -u github.com/ry/v8worker2
cd $GOPATH/src/github.com/ry/v8worker2
./build.py --use_ccache

```
out_path None
Rebuilding V8
Fetching dependencies.
Traceback (most recent call last):
  File "./build.py", line 149, in <module>
    main()
  File "./build.py", line 85, in main
    lib_fn = Rebuild()
  File "./build.py", line 97, in Rebuild
    EnsureDeps(v8_path)
  File "./build.py", line 146, in EnsureDeps
    env=env)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
```

**Comment by yuqingc** [comment] 2018-06-01 03:45
There is a error when I run `go get -u github.com/ry/v8worker2`. I ignored this error and went on. It appeared again when I `make` demo.
```
go build -o deno ./cmd
# pkg-config --cflags v8.pc
Failed to open 'v8.pc': No such file or directory
No package 'v8.pc' found
pkg-config: exit status 1
Makefile:39: recipe for target 'deno' failed
make: *** [deno] Error 2
```

What is this `v8.pc` dir for? How can I make it right?
@qti3e

**Comment by qti3e** [comment] 2018-06-01 04:46
@lvgithub to build `v8worker2` you need to [pull git submodules](https://stackoverflow.com/questions/1030169/easy-way-to-pull-latest-of-all-git-submodules):

```bash
cd $GOPATH/src/github.com/ry/v8worker2
git submodule update --recursive --remote
```
and then you can use `./build.py`

**Comment by qti3e** [comment] 2018-06-01 04:53
@yuqingc `v8.pc` is a package-config file which `v8worker2` is using to link V8 with Go.
when you execute `./build.py` it will auto-generate this file and a dir called `out`
so your first issue is that you can't build V8Worker, and it would be solved if you build `v8worker2`
____
```
Failed to fetch file gs://chromium-clang-format/5349d1954e17f6ccafb6e6663b0f13cdb2bb33c8 for v8/buildtools/linux64/clang-format. [Err: Traceback (most recent call last):
```
This is a network connection error (caused by `gclient`), make sure you have a good internet connection, if you don't please let me know and I'll see if I can do anything for you : )

**Comment by qti3e** [comment] 2018-06-01 04:56
@yuqingc btw if you're a Mac os user make sure you have package-config on your system:
`brew install pkg-config`

**Comment by yuqingc** [comment] 2018-06-01 05:26
@qti3e  Thanks. I tried building again but the error of "no v8.pc" raises on `go get -u github.com/ry/v8worker2`.
```
$: ~/go/pkg$ go get -u github.com/ry/v8worker2
# pkg-config --cflags v8.pc
Failed to open 'v8.pc': No such file or directory
No package 'v8.pc' found
pkg-config: exit status 1
```
I assume I should get v8worder2 by `git clone` the original repository directly and then build it manually. I'll update my result in here.
Thanks again for your advice. :smile:

**Comment by qti3e** [comment] 2018-06-01 05:48
@yuqingc Do you still experience following error?
```
Failed to fetch file gs://chromium-clang-format/5349d1954e17f6ccafb6e6663b0f13cdb2bb33c8 for v8/buildtools/linux64/clang-format. [Err: Traceback (most recent call last):
```
also can you please make sure you have somefiles in `depot_tools`?
try: `ls  $GOPATH/src/github.com/ry/v8worker2/depot_tools`

if there is nothing in there please try:
```
cd $GOPATH/src/github.com/ry/v8worker2
git submodule update --init
```

**Comment by yuqingc** [comment] 2018-06-01 06:01
@qti3e There are files in `$GOPATH/src/github.com/ry/v8worker2/depot_tools`
I am building v8worker2. It takes time and I'll update the building status whether or not there is `Failed to fetch file` later.
btw. Since `./build.py` auto-generates `v8.pc`, why does the `cannot find v8.pc` error was invoked at the `go get` stage, before `./build.py` process?

**Comment by lvgithub** [comment] 2018-06-01 08:12
@qti3e  I succeeded in solving the problem,when is run 'git submodule update --init' before run '.build.py',but has error ：
```
Running hooks: 100% (28/28), done.
Running gn
ERROR at //build/config/mac/mac_sdk.gni:55:5: Script returned non-zero exit code.
    exec_script("//build/mac/find_sdk.py", find_sdk_args, "list lines")
    ^----------
Current dir: /Users/liuwei74/go/src/github.com/ry/v8worker2/out/v8build/
Command: python -- /Users/liuwei74/go/src/github.com/ry/v8worker2/v8/build/mac/find_sdk.py --print_sdk_path 10.12
Returned 1.
stderr:

Traceback (most recent call last):
  File "/Users/liuwei74/go/src/github.com/ry/v8worker2/v8/build/mac/find_sdk.py", line 104, in <module>
    print main()
  File "/Users/liuwei74/go/src/github.com/ry/v8worker2/v8/build/mac/find_sdk.py", line 71, in main
    'to continue.')
__main__.SdkError: 'Install Xcode, launch it, accept the license agreement, and run `sudo xcode-select -s /path/to/Xcode.app` to continue.'

See //build/toolchain/mac/BUILD.gn:14:1: whence it was imported.
import("//build/config/mac/mac_sdk.gni")
^--------------------------------------
See //BUILD.gn:621:1: which caused the file to be included.
action("js2c") {
^---------------
Traceback (most recent call last):
  File "./build.py", line 149, in <module>
    main()
  File "./build.py", line 85, in main
    lib_fn = Rebuild()
  File "./build.py", line 114, in Rebuild
    env=env)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/liuwei74/go/src/github.com/ry/v8worker2/depot_tools/gn', 'gen', '/Users/liuwei74/go/src/github.com/ry/v8worker2/out/v8build', '--args=   is_component_build=false   is_debug=false   libcpp_is_static=false   symbol_level=1   treat_warnings_as_errors=false   use_custom_libcxx=false   use_sysroot=false   v8_deprecation_warnings=false   v8_embedder_string="-v8worker2"   v8_enable_gdbjit=false   v8_enable_i18n_support=false   v8_enable_test_features=false   v8_experimental_extra_library_files=[]   v8_extra_library_files=[]   v8_imminent_deprecation_warnings=false   v8_monolithic=true   v8_static_library=false   v8_target_cpu="x64"   v8_untrusted_code_mitigations=false   v8_use_external_startup_data=false   v8_use_snapshot=true ']' returned non-zero exit status 1
```

**Comment by FrankFang** [comment] 2018-06-01 08:29
1 if you got such error, just use vpn!
```
Failed to fetch file gs://xxxxx
```

2 if you got find_sdk.py, just install Xcode!
3 Check your python version, mine is 2.7

**Comment by ry** [comment] 2018-06-01 08:30
@yuqingc  try `sudo apt-get install libgtk-3-dev pkg-config ccache`

@lvgithub Sounds like you need to do something like this: http://osxdaily.com/2014/02/12/install-command-line-tools-mac-os-x/

**Comment by lvgithub** [comment] 2018-06-01 08:41
@ry Yes, it has been solved

**Comment by yuqingc** [comment] 2018-06-01 08:45
@ry Everything works after I installed those packages. Thanks a lot!
btw, @lvgithub why not add `sudo apt-get install libgtk-3-dev pkg-config ccache` to your [PR](https://github.com/ry/deno/pull/65) in case people meet the same problems as I do.

**Comment by qti3e** [comment] 2018-06-01 08:49
so I close this issue : )

**Closed by qti3e** 2018-06-01 08:49 UTC
Labels: bug, v8worker2

**Comment by hefangshi** [comment] 2018-06-02 06:53
For CentOS

```bash
yum install glib2-devel ccache
```

**Comment by 0123cf** [comment] 2018-06-06 10:16
![image](https://user-images.githubusercontent.com/22963895/41032136-1f1bdd98-69b5-11e8-9c26-81bd02cd3c41.png)
@ry 
`libgtk-3-dev pkg-config ccache`  It has been installed, but it still has this problem. Why?

**Comment by lvgithub** [comment] 2018-06-06 10:54
@0123cf you need run `git submodule update --init`

**Comment by 0123cf** [comment] 2018-06-06 11:19
run

git submodule update --init

result
```
out_path None                                                                                                                                                             
Rebuilding V8                                                                                                                                                             
Fetching dependencies.                                                                                                                                                    
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "fetch" "origin"' in ./v8/third_party/jinja2 failed; will retry after a short nap...                        
 WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "fetch" "origin"' in ./v8/third_party/depot_tools failed; will retry after a short nap...                  
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "fetch" "origin"' in ./v8/third_party/googletest/src failed; will retry after a short nap...                
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "fetch" "origin"' in ./v8/third_party/jinja2 failed; will retry after a short nap...                        
 WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "fetch" "origin"' in ./v8/third_party/depot_tools failed; will retry after a short nap...                  
Syncing projects:  80% (16/20) v8/third_party/depot_tools                                                                                                                 
                                                                                                                                                                          
v8/third_party/icu (ERROR)                                                                                                                                                
----------------------------------------                                                                                                                                  
[0:00:02] Started.                                                                                                                                                        
----------------------------------------                                                                                                                                  
Error: Command 'git rev-list -n 1 HEAD' returned non-zero exit status 128 in ./v8/third_party/icu                                                                         
fatal: mmap failed: Cannot allocate memory                                                                                                                                
                                                                                                                                                                          
Traceback (most recent call last):                                                                                                                                        
  File "./build.py", line 149, in <module>                                                                                                                                
    main()                                                                                                                                                                
  File "./build.py", line 85, in main                                                                                                                                     
    lib_fn = Rebuild()                                                                                                                                                    
  File "./build.py", line 97, in Rebuild                                                                                                                                  
    EnsureDeps(v8_path)                                                                                                                                                   
  File "./build.py", line 146, in EnsureDeps                                                                                                                              
    env=env)                                                                                                                                                              
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call                                                                                                        
    raise CalledProcessError(retcode, cmd)                                                                                                                                
subprocess.CalledProcessError: Command '['gclient', 'sync', '--spec', "solutions = [{'managed': False, 'custom_vars': {'build_for_node': True}, 'url': 'https://chromium.g
ooglesource.com/v8/v8.git', 'custom_deps': {'v8/third_party/catapult': None, 'v8/third_party/colorama/src': None, 'v8/testing/gmock': None, 'v8/tools/swarming_client': No
ne, 'v8/third_party/instrumented_libraries': None, 'v8/tools/gyp': None, 'v8/third_party/android_tools': None, 'v8/test/wasm-js': None, 'v8/test/benchmarks/data': None, '
v8/test/mozilla/data': None, 'v8/tools/luci-go': None, 'v8/test/test262/data': None, 'v8/test/test262/harness': None}, 'deps_file': 'DEPS', 'name': 'v8'}]"]' returned non
-zero exit status 1                                                                                                                                                       
```

@lvgithub

**Comment by ldwonday** [comment] 2018-06-07 05:42
@0123cf I meet the same problem!

**Comment by 0123cf** [comment] 2018-06-07 08:35
@ry @FrankFang help me

```
out_path None                                                                                                                                                             
Rebuilding V8                                                                                                                                                             
Fetching dependencies.                                                                                                                                                    
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "fetch" "origin"' in ./v8/third_party/jinja2 failed; will retry after a short nap...                        
 WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "fetch" "origin"' in ./v8/third_party/depot_tools failed; will retry after a short nap...                  
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "fetch" "origin"' in ./v8/third_party/googletest/src failed; will retry after a short nap...                
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "fetch" "origin"' in ./v8/third_party/jinja2 failed; will retry after a short nap...                        
 WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "fetch" "origin"' in ./v8/third_party/depot_tools failed; will retry after a short nap...                  
Syncing projects:  80% (16/20) v8/third_party/depot_tools                                                                                                                 
                                                                                                                                                                          
v8/third_party/icu (ERROR)                                                                                                                                                
----------------------------------------                                                                                                                                  
[0:00:02] Started.                                                                                                                                                        
----------------------------------------                                                                                                                                  
Error: Command 'git rev-list -n 1 HEAD' returned non-zero exit status 128 in ./v8/third_party/icu                                                                         
fatal: mmap failed: Cannot allocate memory                                                                                                                                
                                                                                                                                                                          
Traceback (most recent call last):                                                                                                                                        
  File "./build.py", line 149, in <module>                                                                                                                                
    main()                                                                                                                                                                
  File "./build.py", line 85, in main                                                                                                                                     
    lib_fn = Rebuild()                                                                                                                                                    
  File "./build.py", line 97, in Rebuild                                                                                                                                  
    EnsureDeps(v8_path)                                                                                                                                                   
  File "./build.py", line 146, in EnsureDeps                                                                                                                              
    env=env)                                                                                                                                                              
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call                                                                                                        
    raise CalledProcessError(retcode, cmd)                                                                                                                                
subprocess.CalledProcessError: Command '['gclient', 'sync', '--spec', "solutions = [{'managed': False, 'custom_vars': {'build_for_node': True}, 'url': 'https://chromium.g
ooglesource.com/v8/v8.git', 'custom_deps': {'v8/third_party/catapult': None, 'v8/third_party/colorama/src': None, 'v8/testing/gmock': None, 'v8/tools/swarming_client': No
ne, 'v8/third_party/instrumented_libraries': None, 'v8/tools/gyp': None, 'v8/third_party/android_tools': None, 'v8/test/wasm-js': None, 'v8/test/benchmarks/data': None, '
v8/test/mozilla/data': None, 'v8/tools/luci-go': None, 'v8/test/test262/data': None, 'v8/test/test262/harness': None}, 'deps_file': 'DEPS', 'name': 'v8'}]"]' returned non
-zero exit status 1                         
```

**Comment by FrankFang** [comment] 2018-06-08 16:09
@0123cf  Try vpn.
