### ISSUE TITLE
Cannot run testdata/006

### ISSUE THREAD

**Issue by monkingxue** [ry/deno#62] opened 2018-06-01 04:32 UTC
Hi bro, I have configured the environment and run the deno, but I cannot pass the 6th test case, and the following is screenshot of terminal: 
![image](https://user-images.githubusercontent.com/16385790/40821165-cd2868ba-6597-11e8-95d3-f2ec9794c187.png)

**Comment by yuqingc** [comment] 2018-06-01 05:18
It seems that this package is imported from a server. Since there is no server running at 4545 port on your local computer which serves the exact ts file, it might fail importing modules from that url.

**Comment by monkingxue** [comment] 2018-06-01 05:35
@yuqingc Yeah, I also find this problem, but the error message is `An import path cannot end with a '.ts'`, this isn't the real problem, is it?

**Comment by yorkie** [comment] 2018-06-01 05:49
The server is up already, because the tests are pass before `06`, it seems like an issue about import on TypeScript.

**Comment by qti3e** [comment] 2018-06-01 05:51
FYI; you'll see this in case of lack of server:
```
Downloading http://localhost:4545/testdata/subdir/print_hello.ts
/main.js:15737
                throw _iteratorError;
                ^
TypeError: Cannot read property 'compileAndRun' of undefined
    at ../runtime.ts:132:19
    at Array.map (<anonymous>)
    at localDefine (../runtime.ts:120:23)
    at eval (/home/qti3e/go/src/deno/testdata/006_url_imports.ts, <anonymous>)
    at Object.eval [as globalEval] (<anonymous>)
    at execute (../runtime.ts:185:3)
    at FileModule.compileAndRun (../runtime.ts:93:5)
    at ../main.ts:50:9
    at ../dispatch.ts:68:5
```

**Comment by monkingxue** [comment] 2018-06-01 06:02
@qti3e Yeah, if I run `make test`, all of tests are ok because the `test.go` will start a server. But when I use `deno testdata/006_.....`,  the error message isn't something about lacking of server, although I didn't start the server.

**Comment by monkingxue** [comment] 2018-06-01 06:06
@yorkie The tests before 006 don't use importing by url, so they can pass

**Comment by qti3e** [comment] 2018-06-01 06:07
@monkingxue that's because Deno cache the files and doesn't send a network request.. (look at `~/.deno/src`)

**Comment by monkingxue** [comment] 2018-06-01 06:28
@qti3e Absolutely right, `typescript version 2.8.3`.But I find the `print_hello.ts` file in `.deno/cache` rather than `.deno/src`

**Comment by qti3e** [comment] 2018-06-01 06:33
@mohsen1 So error is not related to TypeScript version as I have the same version...
btw, the file should be in `~/.deno/src/localhost:4545/testdata/subdir/print_hello.ts`
if it's not maybe the issue is related to this?

**Comment by monkingxue** [comment] 2018-06-01 06:35
@qti3e I have removed the cache file and src file, and just re-run the `deno 006...` but it still told me that `An import path cannot end with a '.ts' extension`

**Comment by monkingxue** [comment] 2018-06-01 06:40
![image](https://user-images.githubusercontent.com/16385790/40825257-a81d6ebe-65a9-11e8-8747-a3a178a94687.png)

**Comment by qti3e** [comment] 2018-06-01 06:57
Ok! I've could reproduce the error :tada:
while you run `make test` Deno uses a diffrent cache dir:
https://github.com/ry/deno/blob/180f0a1b3cfa0f7cd1f37485839c763de4d03693/integration_test.go#L73-L86

so it can't use this cached file later when you want to execute code by your self : (
so you should do:
```
cd $GOPATH/src/github.com/deno
http-server -p 4545
```
and then try the code again (`deno testdata/006/...`), after that close your `http-server`
now you can try the code again and it should just work...

I'll close this as resolved : )

**Closed by qti3e** 2018-06-01 06:57 UTC
Labels: bug

**Comment by monkingxue** [comment] 2018-06-01 07:05
@qti3e, Yeah it's all right, but I think the error message should be `lack of server` when I didn't run the server port 4545.

**Comment by ulivz** [comment] 2018-06-01 08:03
@qti3e Reproduced this error and resolved this error as you mentioned. thanks!
