### ISSUE TITLE
APIs proposal

### ISSUE THREAD

**Issue by sbFrankFang** [ry/deno#84] opened 2018-06-01 12:46 UTC
@ry @qti3e I just have a proposal about which Web APIs should be supported:
High level
  Console
  File/FileList/FileReader/Blob
  XMLHttpRequest
  WebSocket
Middle level
  AudioContext/AudioBuffer
  Canvas
Btw, supports WebGL that makes like tfjs could run at deno, and make use of the GPUs, it might be interesting personally :)

and your code is very six, i must give you double click,six six six.

Wait until I have the many money to send you a plane and a yacht.

We work together, come on!

**Comment by 44886** [comment] 2018-06-01 12:48
very good

**Comment by lopo1983** [comment] 2018-06-01 12:48
tree new bee 👍

**Comment by qti3e** [comment] 2018-06-01 12:53
duplicate of #82

**Closed by qti3e** 2018-06-01 12:53 UTC

**Comment by FrankFang** [comment] 2018-06-01 12:54
It's not me
